# paths relative to package directory
paths:
  etc_folder: "etc"
  eva_schema_file: "etc/eva_schema.json"
  dgva_schema_file: "etc/dgva_schema.json"
  test_folder: "../tests"
# external paths relative to package directory
assembly_paths:
  GRCh37: "${REF_PATH}/homo_sapiens/GCA_000001405.1/GCA_000001405.1.fa"
  GRCh37.p13: "${REF_PATH}/homo_sapiens/GCA_000001405.14/GCA_000001405.14.fa"
  GRCh38: "${REF_PATH}/homo_sapiens/GCA_000001405.15/GCA_000001405.15.fa"
  NCBI35: "${REF_PATH}/homo_sapiens/GCF_000001405.11/GCF_000001405.11.fa"
  NCBI36: "${REF_PATH}/homo_sapiens/GCF_000001405.12/GCF_000001405.12.fa"
assembly_report_paths:
  GRCh37: "${REF_PATH}/homo_sapiens/GCA_000001405.1/GCA_000001405.1_assembly_report.txt"
  GRCh37.p13: "${REF_PATH}/homo_sapiens/GCA_000001405.14/GCA_000001405.14_assembly_report.txt"
  GRCh38: "${REF_PATH}/homo_sapiens/GCA_000001405.15/GCA_000001405.15_assembly_report.txt"
  NCBI35: "${REF_PATH}/homo_sapiens/GCF_000001405.11/GCF_000001405.11_assembly_report.txt"
  NCBI36: "${REF_PATH}/homo_sapiens/GCF_000001405.12/GCF_000001405.12_assembly_report.txt"
assembly_accession:
  GRCh37: "GCA_000001405.1"
  GRCh37.p13: "GCA_000001405.14"
  GRCh38: "GCA_000001405.15"
  NCBI35: "GCF_000001405.11"
  NCBI36: "GCF_000001405.12"